// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdMf8LwT_pYYUIkR9YhmxilVQtMOL6alQ',
    appId: '1:206768939725:web:9c07fa7f641c49bb053f84',
    messagingSenderId: '206768939725',
    projectId: 'para-pilot',
    authDomain: 'para-pilot.firebaseapp.com',
    storageBucket: 'para-pilot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCom-oCo4g5Bm-BvuEMW7BlE7TtgnVWQqQ',
    appId: '1:206768939725:android:2255032ba87cb6b1053f84',
    messagingSenderId: '206768939725',
    projectId: 'para-pilot',
    storageBucket: 'para-pilot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa4GIQZqgv4mSthJmyvmrr340GSYWRKdE',
    appId: '1:206768939725:ios:1ef9c4d4c882bc02053f84',
    messagingSenderId: '206768939725',
    projectId: 'para-pilot',
    storageBucket: 'para-pilot.appspot.com',
    iosBundleId: 'com.example.paraPilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa4GIQZqgv4mSthJmyvmrr340GSYWRKdE',
    appId: '1:206768939725:ios:d3c96790f6fb38c4053f84',
    messagingSenderId: '206768939725',
    projectId: 'para-pilot',
    storageBucket: 'para-pilot.appspot.com',
    iosBundleId: 'com.example.paraPilot.RunnerTests',
  );
}
